// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: file_meta.proto

package files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkInfo) Reset() {
	*x = ChunkInfo{}
	mi := &file_file_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkInfo) ProtoMessage() {}

func (x *ChunkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkInfo.ProtoReflect.Descriptor instead.
func (*ChunkInfo) Descriptor() ([]byte, []int) {
	return file_file_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkInfo) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ChunkInfo) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ChunkInfo     map[string]*ChunkInfo  `protobuf:"bytes,3,rep,name=chunkInfo,proto3" json:"chunkInfo,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_file_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_file_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_file_meta_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMetadata) GetChunkInfo() map[string]*ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

var File_file_meta_proto protoreflect.FileDescriptor

const file_file_meta_proto_rawDesc = "" +
	"\n" +
	"\x0ffile_meta.proto\x12\x05files\"7\n" +
	"\tChunkInfo\x12\x12\n" +
	"\x04size\x18\x01 \x01(\rR\x04size\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\xc8\x01\n" +
	"\fFileMetadata\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12@\n" +
	"\tchunkInfo\x18\x03 \x03(\v2\".files.FileMetadata.ChunkInfoEntryR\tchunkInfo\x1aN\n" +
	"\x0eChunkInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.files.ChunkInfoR\x05value:\x028\x01B1Z/github.com/lokeshMudhalvan/MyDFS/internal/filesb\x06proto3"

var (
	file_file_meta_proto_rawDescOnce sync.Once
	file_file_meta_proto_rawDescData []byte
)

func file_file_meta_proto_rawDescGZIP() []byte {
	file_file_meta_proto_rawDescOnce.Do(func() {
		file_file_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_meta_proto_rawDesc), len(file_file_meta_proto_rawDesc)))
	})
	return file_file_meta_proto_rawDescData
}

var file_file_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_file_meta_proto_goTypes = []any{
	(*ChunkInfo)(nil),    // 0: files.ChunkInfo
	(*FileMetadata)(nil), // 1: files.FileMetadata
	nil,                  // 2: files.FileMetadata.ChunkInfoEntry
}
var file_file_meta_proto_depIdxs = []int32{
	2, // 0: files.FileMetadata.chunkInfo:type_name -> files.FileMetadata.ChunkInfoEntry
	0, // 1: files.FileMetadata.ChunkInfoEntry.value:type_name -> files.ChunkInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_file_meta_proto_init() }
func file_file_meta_proto_init() {
	if File_file_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_meta_proto_rawDesc), len(file_file_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_meta_proto_goTypes,
		DependencyIndexes: file_file_meta_proto_depIdxs,
		MessageInfos:      file_file_meta_proto_msgTypes,
	}.Build()
	File_file_meta_proto = out.File
	file_file_meta_proto_goTypes = nil
	file_file_meta_proto_depIdxs = nil
}
